### PR TITLE
Update to support InteractionObject

### PR DESCRIPTION
**Pull request by parker02311**
Adds support for the new InteractionObject class.

This was a very simple implementation and I am sure there are things you could improve, but it keeps the same structure that the current code uses.

### CODE REVIEW

**Comment by redthirten** [comment]
Hey! Thank you so much for the PR! I haven't had a chance to fully test or review the code, but it looks good after a quick skim. I also appreciate you keeping the same rough structure of the code (helps me review it faster). My college semester is almost finished, so I will fully review and merge this when I'm free. Lastly, I think I still need to remove the green indicator balls from the models, so I will probably merge this into a `dev` branch first for some additional, small cleanup on my part before making a full release on `main`.

**Comment by parker02311** [comment]
> Hey! Thank you so much for the PR! I haven't had a chance to fully test or review the code, but it looks good after a quick skim. I also appreciate you keeping the same rough structure of the code (helps me review it faster). My college semester is almost finished, so I will fully review and merge this when I'm free. Lastly, I think I still need to remove the green indicator balls from the models, so I will probably merge this into a `dev` branch first for some additional, small cleanup on my part before making a full release on `main`.

I also just realized I need to remove the redundant Raycast script now that it's not used. I'll get to that tonight.

**Comment by parker02311** [comment]
Was this closed on purpose?

**Comment by redthirten** [comment]
Sorry, made a local vs. remote branch oopsie...

**Comment by parker02311** [comment]
> Sorry, made a local vs. remote branch oopsie...

All good I just saw the email and was confused.

**Review by redthirten — APPROVED** [review]
Hey. So sorry for the long wait. I have finally found some time to look at this and develop it further. Like I said previously, this looks like a great start and I appreciate the work done. I will merge this to a dev branch now for some additional development and clean up (ie. remove the Raycast class and remove the click indicators on the models). Once I am done, I will merge the dev branch to main as a new release and credit you accordingly. Thanks again!

**Pull request merged**
